#ifndef DATA_PROCESSORS_SYNAPSE_VERSION_H
#define DATA_PROCESSORS_SYNAPSE_VERSION_H

#define DATA_PROCESSORS_STRINGIFY_IMPL(String) #String
#define DATA_PROCESSORS_STRINGIFY(String) DATA_PROCESSORS_STRINGIFY_IMPL(String)

#ifndef DATA_PROCESSORS_PROPER_BUILDING_INFRASTRUCTURE
#define BUILD_INFO "MANUAL BUILD NOT FOR DEPLOYMENT"
#define MY_VERSION "MANUAL BUILD NOT FOR DEPLOYMENT"
#else

#include "Svn_info.h"

#define DATA_PROCESSORS_SYNAPSE_VERSION_MAJOR 0
#define DATA_PROCESSORS_SYNAPSE_VERSION_MINOR 0
#define DATA_PROCESSORS_SYNAPSE_VERSION_PATCH 0

#define MY_VERSION DATA_PROCESSORS_STRINGIFY(DATA_PROCESSORS_SYNAPSE_VERSION_MAJOR) "." DATA_PROCESSORS_STRINGIFY(DATA_PROCESSORS_SYNAPSE_VERSION_MINOR) "." DATA_PROCESSORS_STRINGIFY(DATA_PROCESSORS_SYNAPSE_VERSION_PATCH)


#ifndef NDEBUG
	#define DATA_PROCESSORS_BUILD_VARIANT "DEBUG"
#else
	#define DATA_PROCESSORS_BUILD_VARIANT "RELEASE"
#endif

#ifdef SYNAPSE_SINGLE_THREADED 
	#define DATA_PROCESSORS_BUILD_THREADING "SINGLETHREADED"
#else
	#define DATA_PROCESSORS_BUILD_THREADING "MULTITHREADED"
#endif

#define BUILD_INFO "BUILD info: " MY_VERSION " " DATA_PROCESSORS_BUILD_VARIANT " " DATA_PROCESSORS_BUILD_THREADING " " SVN_INFO " compiled date/time: " __DATE__ " " __TIME__ 

// more macros __FILE__  

#endif

char const static Version_string_with_newline[] = BUILD_INFO "\n";

#endif
